apiVersion: batch/v1
kind: CronJob
metadata:
  name: draftstore-cleanup
  namespace: draftstore
  labels:
    app: draftstore-cleanup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  jobTemplate:
    metadata:
      labels:
        app: draftstore-cleanup
    spec:
      activeDeadlineSeconds: 3600  # 1 hour timeout
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: draftstore-cleanup
        spec:
          containers:
          - name: cleanup
            image: draftstore-cronjob:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: draftstore-config
            - secretRef:
                name: aws-credentials
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
          securityContext:
            fsGroup: 1000
          restartPolicy: OnFailure
