apiVersion: v1
kind: Service
metadata:
  name: draftstore-service
  namespace: draftstore
  labels:
    app: draftstore-server
spec:
  selector:
    app: draftstore-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: draftstore-service-internal
  namespace: draftstore
  labels:
    app: draftstore-server
spec:
  selector:
    app: draftstore-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
